### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by xfliu1995** [Weeks-UNC/shapemapper2#11]
Too much memory is occupied by software operation, when mapping by STAR. This often causes software to fail.How do you limit the maximum amount of memory that your software can use while it is running?

**Comment by shapemapper** [comment]
What are your alignment target sequences? 

If you're attempting to align against a large number of transcripts, see [FAQ](https://github.com/Weeks-UNC/shapemapper2/blob/master/docs/FAQ.md#can-i-run-shapemapper-on-multiple-rnas-at-the-same-time). On the other hand, if you're trying to align against a small number of large sequences (for example the human genome), the aligner index will just require a lot of memory (~30Gb in the case of the human genome), and that's not easily worked around without changing the aligner.

**Comment by shapemapper** [comment]
I should also add that you can adjust the speed/memory tradeoff with the `--genomeSAindexNbase` parameter, which is passed through to STAR during the genome index building phase.

**Comment by xfliu1995** [comment]
When I add --genomeSAindexNbase parameter for shapemapper2，shapemapper2 running error.
Traceback (most recent call last):
  File "/BioII/lulab_b/shibinbin/projects/shapemap/python/cli.py", line 108, in <module>
    run(sys.argv)
  File "/BioII/lulab_b/shibinbin/projects/shapemap/python/cli.py", line 46, in run
    pipeline = ap.construct(rest_args)
  File "/BioII/lulab_b/shibinbin/projects/shapemap/python/pyshapemap/pipeline_arg_parser.py", line 595, in construct
    params, fastqs = parse_args(args)
  File "/BioII/lulab_b/shibinbin/projects/shapemap/python/pyshapemap/pipeline_arg_parser.py", line 440, in parse_args
    raise RuntimeError("Error: unrecognized argument(s): {}".format(rest))
RuntimeError: Error: unrecognized argument(s): ['--genomeSAindexNbases']

**Comment by shapemapper** [comment]
Are you running the most recent version of shapemapper?
