### ISSUE TITLE
Component "Tab6Interleaver" (sample:Modified) failed

### ISSUE THREAD

**Issue by SooLee** [Weeks-UNC/shapemapper2#26]
Hi, I'm getting the following error while running the pre-compiled tarball on Ubuntu 20.04. 

```bash
./run_example.sh
```
```
Started ShapeMapper v2.1.5 at 2021-12-14 15:42:36
Output will be logged to example-results_shapemapper_log.txt
Running from directory: /d/shapemapper-2.1.5
args:  --name example-results --target example_data/TPP.fa --amplicon --overwrite --min-depth 1000 --modified --folder example_data/TPPplus --untreated --folder example_data/TPPminus --denatured --folder example_data/TPPdenat
Created pipeline at 2021-12-14 15:42:37
Running PrimerLocator at 2021-12-14 15:42:37 . . .
. . . done at 2021-12-14 15:42:38
Running FastaFormatChecker at 2021-12-14 15:42:38 . . .
. . . done at 2021-12-14 15:42:38
Running BowtieIndexBuilder at 2021-12-14 15:42:38 . . .
. . . done at 2021-12-14 15:42:41
Running process group 4 at 2021-12-14 15:42:41 . . .
  Including these components:
    Appender1 . . . started at 2021-12-14 15:42:41
    Appender2 . . . started at 2021-12-14 15:42:41
    ProgressMonitor . . . started at 2021-12-14 15:42:41
    QualityTrimmer1 . . . started at 2021-12-14 15:42:41
    QualityTrimmer2 . . . started at 2021-12-14 15:42:41
    Interleaver . . . started at 2021-12-14 15:42:41
    Merger . . . started at 2021-12-14 15:42:41
    Tab6Interleaver . . . started at 2021-12-14 15:42:41
    BowtieAligner . . . started at 2021-12-14 15:42:41
    MutationParser_Modified . . . started at 2021-12-14 15:42:41
    MutationCounter_Modified . . . started at 2021-12-14 15:42:41
  635KiB [============================================================>] 100%                 
ERROR: Component "Tab6Interleaver" (sample:Modified) failed, giving the following error message:
Traceback (most recent call last):
  File "/d/shapemapper-2.1.5/internals/python/pyshapemap/../../bin/tab6_interleave.py", line 62, in <module>
    for reads in gen():
  File "/d/shapemapper-2.1.5/internals/python/pyshapemap/../../bin/tab6_interleave.py", line 37, in gen
    for r in iterate_fastq(pa.input):
  File "/d/shapemapper-2.1.5/internals/python/pyshapemap/../../bin/tab6_interleave.py", line 22, in iterate_fastq
    l = [lines[0][1:].split()[0], lines[1].strip(), lines[3].strip()]
IndexError: list index out of range
```

**Comment by noahpieta** [comment]
Hi, is  there anyone have solved this issue? I come across the same one. Thanks!
