### ISSUE TITLE
Sequence corrector error

### ISSUE THREAD

**Issue by jodyphelan** [Weeks-UNC/shapemapper2#28]
The pipeline is exiting with the following error:

```
/mnt/storage8/jody/software/shapemapper-2.1.5/internals/python/pyshapemap/../../bin/make_variant.py:245: RuntimeWarning: divide by zero encountered in long_scalars
  freq = variant.count / d
Traceback (most recent call last):
  File "/mnt/storage8/jody/software/shapemapper-2.1.5/internals/python/pyshapemap/../../bin/make_variant.py", line 433, in <module>
    merged_variants)
  File "/mnt/storage8/jody/software/shapemapper-2.1.5/internals/python/pyshapemap/../../bin/make_variant.py", line 328, in correct_sequence
    raise RuntimeError(s)
RuntimeError: Error: Unable to determine variant sequence. Conflicting (overlapping) variant sequences present.
```

Is there something wrong with the command I am using?
```
shapemapper --name example --target ~/ref.fa --out test --correct-seq --folder minus --modified --folder pos --untreated --folder minus --denatured --folder denatured --nproc 60 --star-aligner
```

**Comment by Psirving** [comment]
Sorry for not replying sooner. Your command looks correct. The error `Conflicting (overlapping) variant sequences present.` indicates that there may be multiple sequence variants in the untreated sample, and ShapeMapper could not find a unique corrected sequence. Were you able to resolve this?
