### ISSUE TITLE
problem with sequence corrector

### ISSUE THREAD

**Issue by irinatu** [Weeks-UNC/shapemapper2#37]
I have Error message that I do not understand completely. Could you help me, please?

Running SequenceCorrector at 2022-11-03 11:25:43 . . .

ERROR: Component "SequenceCorrector" failed, giving the following error message:==============================================================
Traceback (most recent call last):
  File "/home/irina/bin/shapemapper-2.1.5/internals/python/pyshapemap/../../bin/make_variant.py", line 430, in <module>
    merged_variants)
  File "/home/irina/bin/shapemapper-2.1.5/internals/python/pyshapemap/../../bin/make_variant.py", line 325, in correct_sequence
    raise RuntimeError(s)
RuntimeError: Error: Unable to determine variant sequence. Conflicting (overlapping) variant sequences present.

**Comment by Psirving** [comment]
I'm not entirely certain, but I think this means that SequenceCorrector is detecting multiple variants and that they are too different to merge into a single "correct" sequence. For example, if there were two alleles that are multiple SNPs away from the provided fasta in different directions, it might produce this error.

**Comment by irinatu** [comment]
Thank you for a prompt reply.
Best regards,
Irina.

From: Patrick Irving ***@***.***>
Date: Thursday, 3 November 2022 at 17:15
To: Weeks-UNC/shapemapper2 ***@***.***>
Cc: irinatu ***@***.***>, Author ***@***.***>
Subject: Re: [Weeks-UNC/shapemapper2] problem with sequence corrector (Issue #37)

I'm not entirely certain, but I think this means that SequenceCorrector is detecting multiple variants and that they are too different to merge into a single "correct" sequence. For example, if there were two alleles that are multiple SNPs away from the provided fasta in different directions, it might produce this error.
