### ISSUE TITLE
CalcProfile numpy error

### ISSUE THREAD

**Issue by DollyCM** [Weeks-UNC/shapemapper2#58]
Hello,
I am using SHAPEmapper2.2 for my RNA structure probing analyses and I am getting the following error for calculating profile from mutations. It gives the following error irrespective of python version.
Could you kindly help resolve this error?

Partial Log output:  
/storage/workspaces/ips_reislab/reislab/Software/shapemapper2/internals/python/pyshapemap/../../bin/make_reactivity_profiles.py:208: DeprecationWarning: 'U' mode is deprecated
  f = open(fastaname, "rU")
/storage/workspaces/ips_reislab/reislab/Software/shapemapper2/internals/python/pyshapemap/../../bin/make_reactivity_profiles.py:240: DeprecationWarning: 'U' mode is deprecated
  f = open(filename, "rU")
Traceback (most recent call last):
  File "/storage/workspaces/ips_reislab/reislab/Software/shapemapper2/internals/python/pyshapemap/../../bin/make_reactivity_profiles.py", line 425, in <module>
    addtl_column_names = load_counts(p.counts[i])
  File "/storage/workspaces/ips_reislab/reislab/Software/shapemapper2/internals/python/pyshapemap/../../bin/make_reactivity_profiles.py", line 330, in load_counts
    counts = np.zeros(length, dtype=np.int)
  File "/storage/homefs/dm23z608/.local/lib/python3.9/site-packages/numpy/__init__.py", line 394, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by rmrodell** [comment]
You have probably moved on from this, but this is still an error as of the posting of this comment and I thought I would mention how I resolved it. I did as it suggested, replacing `np.int` with `np.int64` where it appears in the internals/make_reactivity_profiles.py file.
