### ISSUE TITLE
Unhelpful error message when R1 fastq missing

### ISSUE THREAD

**Issue by shapemapper** [Weeks-UNC/shapemapper2#6]
If an R2 fastq is present in an input folder specified with --folder, but an R1 fastq is missing/not present, the following unhelpful error message is generated:

Traceback (most recent call last):
  File "/home/ubuntu/shapemapper-2.1.4/internals/python/cli.py", line 141, in <module>
    run(sys.argv)
  File "/home/ubuntu/shapemapper-2.1.4/internals/python/cli.py", line 51, in run
    pipeline, arg_dict = ap.construct(rest_args)
  File "/home/ubuntu/shapemapper-2.1.4/internals/python/pyshapemap/pipeline_arg_parser.py", line 522, in construct
    return (build_pipeline(**kw),
  File "/home/ubuntu/shapemapper-2.1.4/internals/python/pyshapemap/pipeline_builder.py", line 422, in build_pipeline
    pipeline.setup()
  File "/home/ubuntu/shapemapper-2.1.4/internals/python/pyshapemap/pipeline.py", line 514, in setup
    self.gen_filenames(path=temp)
  File "/home/ubuntu/shapemapper-2.1.4/internals/python/pyshapemap/pipeline.py", line 444, in gen_filenames
    node.filename = gen_name(node)
  File "/home/ubuntu/shapemapper-2.1.4/internals/python/pyshapemap/pipeline.py", line 414, in gen_name
    extension = node.get_extension()
  File "/home/ubuntu/shapemapper-2.1.4/internals/python/pyshapemap/nodes.py", line 72, in get_extension
    return self.input_node.get_extension()
  File "/home/ubuntu/shapemapper-2.1.4/internals/python/pyshapemap/nodes.py", line 258, in get_extension
    return self.parent_component.input_nodes[0].get_extension()
IndexError: list index out of range

**Comment by shapemapper** [comment]
fixed in 2.1.5
